import { ethers } from "ethers";

import { CHAIN_IDs, TOKEN_SYMBOLS_MAP } from "../../../_constants";
import { CCTP_SUPPORTED_CHAINS } from "../../cctp/utils/constants";
import { getEnvs } from "../../../_env";

// NOTE: For now, we always use fast CCTP mode
export const CCTP_TRANSFER_MODE = "fast" as const;

export const SPONSORED_CCTP_QUOTE_FINALIZER_ADDRESS =
  getEnvs().SPONSORED_CCTP_QUOTE_FINALIZER_ADDRESS ||
  ethers.constants.AddressZero;

export const SPONSORED_CCTP_SRC_PERIPHERY_ADDRESSES = {
  [CHAIN_IDs.ARBITRUM]: "0xce1FFE01eBB4f8521C12e74363A396ee3d337E1B",
  [CHAIN_IDs.BASE]: "0xA7A8d1efC1EE3E69999D370380949092251a5c20",
  [CHAIN_IDs.ARBITRUM_SEPOLIA]: "0x79176E2E91c77b57AC11c6fe2d2Ab2203D87AF85",
  [CHAIN_IDs.SOLANA_DEVNET]: "CPr4bRvkVKcSCLyrQpkZrRrwGzQeVAXutFU8WupuBLXq",
};

export const SPONSORED_CCTP_DST_PERIPHERY_ADDRESSES = {
  [CHAIN_IDs.HYPEREVM]: "0x7A64A0B796bDb99409803EE427186942c7b70C39",
  [CHAIN_IDs.HYPEREVM_TESTNET]: "0x06C61D54958a0772Ee8aF41789466d39FfeaeB13",
};

export const SPONSORED_CCTP_ORIGIN_CHAINS = CCTP_SUPPORTED_CHAINS.filter(
  (chainId) =>
    ![
      CHAIN_IDs.HYPERCORE,
      CHAIN_IDs.HYPERCORE_TESTNET,
      CHAIN_IDs.HYPEREVM,
      CHAIN_IDs.HYPEREVM_TESTNET,
    ].includes(chainId)
);

export const SPONSORED_CCTP_INPUT_TOKENS = ["USDC"];

export const SPONSORED_CCTP_OUTPUT_TOKENS = ["USDC", "USDH-SPOT"];

export const SPONSORED_CCTP_FINAL_TOKEN_PER_OUTPUT_TOKEN: Record<
  string,
  (typeof TOKEN_SYMBOLS_MAP)[keyof typeof TOKEN_SYMBOLS_MAP]
> = {
  USDC: TOKEN_SYMBOLS_MAP.USDC,
  "USDH-SPOT": TOKEN_SYMBOLS_MAP.USDH,
};

export const SPONSORED_CCTP_DESTINATION_CHAINS = [
  CHAIN_IDs.HYPERCORE,
  CHAIN_IDs.HYPERCORE_TESTNET,
];
