version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Packages that need manual upgrades or should be pinned to a specific version
      - dependency-name: "@across-protocol/sdk"
      - dependency-name: "@across-protocol/contracts"
      - dependency-name: "@across-protocol/constants"
      - dependency-name: "@balancer-labs/sdk"
