// partial abi - only errors
export const SpokePoolErrorAbi = [
  { inputs: [], name: "ClaimedMerkleLeaf", type: "error" },
  { inputs: [], name: "DepositsArePaused", type: "error" },
  { inputs: [], name: "DisabledRoute", type: "error" },
  { inputs: [], name: "ExpiredFillDeadline", type: "error" },
  { inputs: [], name: "FillsArePaused", type: "error" },
  {
    inputs: [],
    name: "InsufficientSpokePoolBalanceToExecuteLeaf",
    type: "error",
  },
  { inputs: [], name: "InvalidBytes32", type: "error" },
  { inputs: [], name: "InvalidChainId", type: "error" },
  { inputs: [], name: "InvalidCrossDomainAdmin", type: "error" },
  { inputs: [], name: "InvalidDepositorSignature", type: "error" },
  { inputs: [], name: "InvalidExclusiveRelayer", type: "error" },
  { inputs: [], name: "InvalidFillDeadline", type: "error" },
  { inputs: [], name: "InvalidMerkleLeaf", type: "error" },
  { inputs: [], name: "InvalidMerkleProof", type: "error" },
  { inputs: [], name: "InvalidPayoutAdjustmentPct", type: "error" },
  { inputs: [], name: "InvalidQuoteTimestamp", type: "error" },
  { inputs: [], name: "InvalidRelayerFeePct", type: "error" },
  { inputs: [], name: "InvalidSlowFillRequest", type: "error" },
  { inputs: [], name: "InvalidWithdrawalRecipient", type: "error" },
  {
    inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
    name: "LowLevelCallFailed",
    type: "error",
  },
  { inputs: [], name: "MaxTransferSizeExceeded", type: "error" },
  { inputs: [], name: "MsgValueDoesNotMatchInputAmount", type: "error" },
  { inputs: [], name: "NoRelayerRefundToClaim", type: "error" },
  { inputs: [], name: "NoSlowFillsInExclusivityWindow", type: "error" },
  { inputs: [], name: "NotCrossChainCall", type: "error" },
  { inputs: [], name: "NotCrossDomainAdmin", type: "error" },
  { inputs: [], name: "NotEOA", type: "error" },
  { inputs: [], name: "NotExclusiveRelayer", type: "error" },
  { inputs: [], name: "RelayFilled", type: "error" },
  { inputs: [], name: "WrongERC7683OrderId", type: "error" },
] as const;
