// Auto-generated file. Do not edit manually.
// Generated on 2025-09-12T16:07:26.238Z
// This file contains available liquidity sources for 0x DEX integration

export const SOURCES = {
  strategy: "0x",
  sources: {
    "1": [
      { key: "0x_RFQ", names: ["0x_rfq"] },
      { key: "Ambient", names: ["ambient"] },
      { key: "Angle", names: ["angle"] },
      { key: "Balancer_V1", names: ["balancer_v1", "balancer"] },
      { key: "Balancer_V2", names: ["balancer_v2", "balancer"] },
      { key: "Balancer_V3", names: ["balancer_v3", "balancer"] },
      { key: "Bancor_V3", names: ["bancor_v3", "bancor"] },
      { key: "Curve", names: ["curve"] },
      { key: "DODO_V1", names: ["dodo_v1", "dodo"] },
      { key: "DODO_V2", names: ["dodo_v2", "dodo"] },
      { key: "DeFi_Swap", names: ["defi_swap"] },
      { key: "Ekubo", names: ["ekubo"] },
      { key: "Fluid", names: ["fluid"] },
      { key: "FluidLite", names: ["fluidlite"] },
      { key: "Fraxswap_V2", names: ["fraxswap_v2", "fraxswap"] },
      { key: "Integral", names: ["integral"] },
      { key: "Lido", names: ["lido"] },
      { key: "Maker_PSM", names: ["maker_psm"] },
      { key: "Maverick", names: ["maverick"] },
      { key: "Maverick_V2", names: ["maverick_v2", "maverick"] },
      { key: "Origin", names: ["origin"] },
      { key: "PancakeSwap_V2", names: ["pancakeswap_v2", "pancakeswap"] },
      { key: "PancakeSwap_V3", names: ["pancakeswap_v3", "pancakeswap"] },
      { key: "Polygon_Migration", names: ["polygon_migration"] },
      { key: "RingSwap", names: ["ringswap"] },
      { key: "RocketPool", names: ["rocketpool"] },
      { key: "ShibaSwap", names: ["shibaswap"] },
      { key: "Sky_Migration", names: ["sky_migration"] },
      { key: "Solidly_V3", names: ["solidly_v3", "solidly"] },
      { key: "Spark", names: ["spark"] },
      { key: "Stepn", names: ["stepn"] },
      { key: "SushiSwap", names: ["sushiswap"] },
      { key: "SushiSwap_V3", names: ["sushiswap_v3", "sushiswap"] },
      { key: "Swaap_V2", names: ["swaap_v2", "swaap"] },
      { key: "Synapse", names: ["synapse"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "Yearn", names: ["yearn"] },
      { key: "Yearn_V3", names: ["yearn_v3", "yearn"] },
    ],
    "10": [
      { key: "Balancer_V2", names: ["balancer_v2", "balancer"] },
      { key: "Curve", names: ["curve"] },
      { key: "DackieSwap_V3", names: ["dackieswap_v3", "dackieswap"] },
      { key: "Solidly_V3", names: ["solidly_v3", "solidly"] },
      { key: "SushiSwap_V3", names: ["sushiswap_v3", "sushiswap"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "Velodrome_V2", names: ["velodrome_v2", "velodrome"] },
      { key: "Velodrome_V3", names: ["velodrome_v3", "velodrome"] },
      { key: "WOOFi_V2", names: ["woofi_v2", "woofi"] },
    ],
    "56": [
      { key: "ApeSwap", names: ["apeswap"] },
      { key: "BabyDogeSwap", names: ["babydogeswap"] },
      { key: "BabySwap", names: ["babyswap"] },
      { key: "BakerySwap", names: ["bakeryswap"] },
      { key: "BiSwap_V2", names: ["biswap_v2", "biswap"] },
      { key: "BiSwap_V3", names: ["biswap_v3", "biswap"] },
      { key: "DODO_V2", names: ["dodo_v2", "dodo"] },
      { key: "DinosaurEggs", names: ["dinosaureggs"] },
      { key: "Fraxswap_V2", names: ["fraxswap_v2", "fraxswap"] },
      { key: "IziSwap", names: ["iziswap"] },
      { key: "MDEX", names: ["mdex"] },
      { key: "Maverick", names: ["maverick"] },
      { key: "Maverick_V2", names: ["maverick_v2", "maverick"] },
      { key: "Nomiswap_Stable", names: ["nomiswap_stable"] },
      { key: "Orion_V2", names: ["orion_v2", "orion"] },
      { key: "PancakeSwap_Stable", names: ["pancakeswap_stable"] },
      { key: "PancakeSwap_V2", names: ["pancakeswap_v2", "pancakeswap"] },
      { key: "PancakeSwap_V3", names: ["pancakeswap_v3", "pancakeswap"] },
      { key: "SquadSwap_V2", names: ["squadswap_v2", "squadswap"] },
      { key: "SquadSwap_V3", names: ["squadswap_v3", "squadswap"] },
      { key: "SushiSwap", names: ["sushiswap"] },
      { key: "Synapse", names: ["synapse"] },
      { key: "Thena", names: ["thena"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "WOOFi_V2", names: ["woofi_v2", "woofi"] },
      { key: "WaultSwap", names: ["waultswap"] },
      { key: "Wombat", names: ["wombat"] },
    ],
    "130": [
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "Velodrome_V2_Mode", names: ["velodrome_v2_mode"] },
      { key: "Velodrome_V3", names: ["velodrome_v3", "velodrome"] },
    ],
    "137": [
      { key: "0x_RFQ", names: ["0x_rfq"] },
      { key: "ApeSwap", names: ["apeswap"] },
      { key: "Balancer_V2", names: ["balancer_v2", "balancer"] },
      { key: "Curve", names: ["curve"] },
      { key: "DODO_V2", names: ["dodo_v2", "dodo"] },
      { key: "Dfyn", names: ["dfyn"] },
      { key: "Fluid", names: ["fluid"] },
      { key: "Meshswap", names: ["meshswap"] },
      { key: "Polycat", names: ["polycat"] },
      { key: "QuickSwap_V2", names: ["quickswap_v2", "quickswap"] },
      { key: "QuickSwap_V3", names: ["quickswap_v3", "quickswap"] },
      { key: "Retro", names: ["retro"] },
      { key: "Stepn", names: ["stepn"] },
      { key: "SushiSwap", names: ["sushiswap"] },
      { key: "SushiSwap_V3", names: ["sushiswap_v3", "sushiswap"] },
      { key: "Synapse", names: ["synapse"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "WOOFi_V2", names: ["woofi_v2", "woofi"] },
      { key: "WaultSwap", names: ["waultswap"] },
    ],
    "480": [
      { key: "DYORSwap", names: ["dyorswap"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "WorldSwap_V2", names: ["worldswap_v2", "worldswap"] },
    ],
    "8453": [
      { key: "0x_RFQ", names: ["0x_rfq"] },
      { key: "Aerodrome_V2", names: ["aerodrome_v2", "aerodrome"] },
      { key: "Aerodrome_V3", names: ["aerodrome_v3", "aerodrome"] },
      { key: "AlienBase_Stable", names: ["alienbase_stable"] },
      { key: "AlienBase_V2", names: ["alienbase_v2", "alienbase"] },
      { key: "AlienBase_V3", names: ["alienbase_v3", "alienbase"] },
      { key: "Angle", names: ["angle"] },
      { key: "Balancer_V2", names: ["balancer_v2", "balancer"] },
      { key: "Balancer_V3", names: ["balancer_v3", "balancer"] },
      { key: "BaseSwap", names: ["baseswap"] },
      { key: "BaseX", names: ["basex"] },
      { key: "Clober_V2", names: ["clober_v2", "clober"] },
      { key: "Curve", names: ["curve"] },
      { key: "DackieSwap_V2", names: ["dackieswap_v2", "dackieswap"] },
      { key: "DackieSwap_V3", names: ["dackieswap_v3", "dackieswap"] },
      { key: "DeltaSwap", names: ["deltaswap"] },
      { key: "Equalizer", names: ["equalizer"] },
      { key: "Fluid", names: ["fluid"] },
      { key: "Hydrex", names: ["hydrex"] },
      { key: "Infusion", names: ["infusion"] },
      { key: "IziSwap", names: ["iziswap"] },
      { key: "Kim_V4", names: ["kim_v4", "kim"] },
      { key: "Kinetix", names: ["kinetix"] },
      { key: "Maverick", names: ["maverick"] },
      { key: "Maverick_V2", names: ["maverick_v2", "maverick"] },
      { key: "Morphex", names: ["morphex"] },
      { key: "Overnight", names: ["overnight"] },
      { key: "PancakeSwap_V2", names: ["pancakeswap_v2", "pancakeswap"] },
      { key: "PancakeSwap_V3", names: ["pancakeswap_v3", "pancakeswap"] },
      { key: "Pinto", names: ["pinto"] },
      { key: "QuickSwap_V4", names: ["quickswap_v4", "quickswap"] },
      { key: "RocketSwap", names: ["rocketswap"] },
      { key: "SharkSwap_V2", names: ["sharkswap_v2", "sharkswap"] },
      { key: "SoSwap", names: ["soswap"] },
      { key: "Solidly_V3", names: ["solidly_v3", "solidly"] },
      { key: "Spark_PSM", names: ["spark_psm"] },
      { key: "SushiSwap", names: ["sushiswap"] },
      { key: "SushiSwap_V3", names: ["sushiswap_v3", "sushiswap"] },
      { key: "Swaap_V2", names: ["swaap_v2", "swaap"] },
      { key: "SwapBased_V3", names: ["swapbased_v3", "swapbased"] },
      { key: "Synapse", names: ["synapse"] },
      { key: "Synthswap_V2", names: ["synthswap_v2", "synthswap"] },
      { key: "Synthswap_V3", names: ["synthswap_v3", "synthswap"] },
      { key: "Thick", names: ["thick"] },
      { key: "Treble", names: ["treble"] },
      { key: "Treble_V2", names: ["treble_v2", "treble"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "WOOFi_V2", names: ["woofi_v2", "woofi"] },
      { key: "Wrapped_BLT", names: ["wrapped_blt"] },
    ],
    "34443": [
      { key: "Balancer_V2", names: ["balancer_v2", "balancer"] },
      { key: "DackieSwap_V3", names: ["dackieswap_v3", "dackieswap"] },
      { key: "IziSwap", names: ["iziswap"] },
      { key: "Kim_V2", names: ["kim_v2", "kim"] },
      { key: "Kim_V4", names: ["kim_v4", "kim"] },
      { key: "Morphex", names: ["morphex"] },
      { key: "SupSwap_V2", names: ["supswap_v2", "supswap"] },
      { key: "SupSwap_V3", names: ["supswap_v3", "supswap"] },
      { key: "SwapMode_V2", names: ["swapmode_v2", "swapmode"] },
      { key: "SwapMode_V3", names: ["swapmode_v3", "swapmode"] },
      { key: "Velodrome_V2_Mode", names: ["velodrome_v2_mode"] },
      { key: "Velodrome_V3", names: ["velodrome_v3", "velodrome"] },
    ],
    "42161": [
      { key: "0x_RFQ", names: ["0x_rfq"] },
      { key: "Angle", names: ["angle"] },
      { key: "ArbSwap", names: ["arbswap"] },
      { key: "Balancer_V2", names: ["balancer_v2", "balancer"] },
      { key: "Balancer_V3", names: ["balancer_v3", "balancer"] },
      { key: "Camelot_V2", names: ["camelot_v2", "camelot"] },
      { key: "Camelot_V3", names: ["camelot_v3", "camelot"] },
      { key: "Curve", names: ["curve"] },
      { key: "DODO_V2", names: ["dodo_v2", "dodo"] },
      { key: "DeltaSwap", names: ["deltaswap"] },
      { key: "Fluid", names: ["fluid"] },
      { key: "GMX_V1", names: ["gmx_v1", "gmx"] },
      { key: "Integral", names: ["integral"] },
      { key: "MIMSwap", names: ["mimswap"] },
      { key: "Maverick_V2", names: ["maverick_v2", "maverick"] },
      { key: "PancakeSwap_V2", names: ["pancakeswap_v2", "pancakeswap"] },
      { key: "PancakeSwap_V3", names: ["pancakeswap_v3", "pancakeswap"] },
      { key: "Ramses", names: ["ramses"] },
      { key: "Ramses_V2", names: ["ramses_v2", "ramses"] },
      { key: "Solidly_V3", names: ["solidly_v3", "solidly"] },
      { key: "SpartaDex", names: ["spartadex"] },
      { key: "SushiSwap", names: ["sushiswap"] },
      { key: "Swapr", names: ["swapr"] },
      { key: "Synapse", names: ["synapse"] },
      { key: "TraderJoe_V2.1", names: ["traderjoe_v2.1", "traderjoe"] },
      { key: "TraderJoe_V2.2", names: ["traderjoe_v2.2", "traderjoe"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
      { key: "WOOFi_V2", names: ["woofi_v2", "woofi"] },
    ],
    "57073": [
      { key: "DYORSwap", names: ["dyorswap"] },
      { key: "InkySwap", names: ["inkyswap"] },
      { key: "Reservoir_V3", names: ["reservoir_v3", "reservoir"] },
      { key: "SquidSwap", names: ["squidswap"] },
      { key: "Velodrome_V2_Mode", names: ["velodrome_v2_mode"] },
      { key: "Velodrome_V3", names: ["velodrome_v3", "velodrome"] },
    ],
    "59144": [
      { key: "Dyson", names: ["dyson"] },
      { key: "EchoDEX_V3", names: ["echodex_v3", "echodex"] },
      { key: "IziSwap", names: ["iziswap"] },
      { key: "Lynex", names: ["lynex"] },
      { key: "Nile", names: ["nile"] },
      { key: "Nile_V2", names: ["nile_v2", "nile"] },
      { key: "Overnight", names: ["overnight"] },
      { key: "PancakeSwap_V3", names: ["pancakeswap_v3", "pancakeswap"] },
      { key: "Secta_V2", names: ["secta_v2", "secta"] },
      { key: "Secta_V3", names: ["secta_v3", "secta"] },
      { key: "SpartaDex", names: ["spartadex"] },
      { key: "SushiSwap_V3", names: ["sushiswap_v3", "sushiswap"] },
      { key: "SyncSwap", names: ["syncswap"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "WOOFi_V2", names: ["woofi_v2", "woofi"] },
      { key: "Xfai", names: ["xfai"] },
    ],
    "81457": [
      { key: "Ambient", names: ["ambient"] },
      { key: "BladeSwap_V2", names: ["bladeswap_v2", "bladeswap"] },
      { key: "BladeSwap_V3", names: ["bladeswap_v3", "bladeswap"] },
      { key: "Blaster_V2", names: ["blaster_v2", "blaster"] },
      { key: "Blaster_V3", names: ["blaster_v3", "blaster"] },
      { key: "CyberBlast_V3", names: ["cyberblast_v3", "cyberblast"] },
      { key: "Fenix_CL", names: ["fenix_cl"] },
      { key: "Fenix_V2", names: ["fenix_v2", "fenix"] },
      { key: "HyperBlast", names: ["hyperblast"] },
      { key: "MIMSwap", names: ["mimswap"] },
      { key: "MonoSwap_V3", names: ["monoswap_v3", "monoswap"] },
      { key: "RingSwap", names: ["ringswap"] },
      { key: "RogueX_V1", names: ["roguex_v1", "roguex"] },
      { key: "RogueX_V2", names: ["roguex_v2", "roguex"] },
      { key: "SwapBlast_V2", names: ["swapblast_v2", "swapblast"] },
      { key: "Thruster_V2_100", names: ["thruster_v2_100", "thruster"] },
      { key: "Thruster_V2_30", names: ["thruster_v2_30", "thruster"] },
      { key: "Thruster_V3", names: ["thruster_v3", "thruster"] },
      { key: "Uniswap_V2", names: ["uniswap_v2", "uniswap"] },
      { key: "Uniswap_V4", names: ["uniswap_v4", "uniswap"] },
    ],
    "534352": [
      { key: "Ambient", names: ["ambient"] },
      { key: "DODO_V2", names: ["dodo_v2", "dodo"] },
      { key: "IziSwap", names: ["iziswap"] },
      { key: "Maverick_V2", names: ["maverick_v2", "maverick"] },
      { key: "Metavault_V2", names: ["metavault_v2", "metavault"] },
      { key: "Metavault_V3", names: ["metavault_v3", "metavault"] },
      { key: "Nuri_CL", names: ["nuri_cl"] },
      { key: "Skydrome", names: ["skydrome"] },
      { key: "SushiSwap_V3", names: ["sushiswap_v3", "sushiswap"] },
      { key: "SyncSwap", names: ["syncswap"] },
      { key: "Tokan", names: ["tokan"] },
      { key: "Uniswap_V3", names: ["uniswap_v3", "uniswap"] },
      { key: "Wombat", names: ["wombat"] },
      { key: "Z_Protocol", names: ["z_protocol"] },
      { key: "Zebra_V2", names: ["zebra_v2", "zebra"] },
    ],
  },
} as {
  strategy: string;
  sources: {
    [chainId: number]: {
      key: string; // Source key used by the DEX API
      names: string[]; // Source names that match the key
    }[];
  };
};

export const ALL_SOURCES = [
  "0x_rfq",
  "aerodrome",
  "aerodrome_v2",
  "aerodrome_v3",
  "alienbase",
  "alienbase_stable",
  "alienbase_v2",
  "alienbase_v3",
  "ambient",
  "angle",
  "apeswap",
  "arbswap",
  "babydogeswap",
  "babyswap",
  "bakeryswap",
  "balancer",
  "balancer_v1",
  "balancer_v2",
  "balancer_v3",
  "bancor",
  "bancor_v3",
  "baseswap",
  "basex",
  "biswap",
  "biswap_v2",
  "biswap_v3",
  "bladeswap",
  "bladeswap_v2",
  "bladeswap_v3",
  "blaster",
  "blaster_v2",
  "blaster_v3",
  "camelot",
  "camelot_v2",
  "camelot_v3",
  "clober",
  "clober_v2",
  "curve",
  "cyberblast",
  "cyberblast_v3",
  "dackieswap",
  "dackieswap_v2",
  "dackieswap_v3",
  "defi_swap",
  "deltaswap",
  "dfyn",
  "dinosaureggs",
  "dodo",
  "dodo_v1",
  "dodo_v2",
  "dyorswap",
  "dyson",
  "echodex",
  "echodex_v3",
  "ekubo",
  "equalizer",
  "fenix",
  "fenix_cl",
  "fenix_v2",
  "fluid",
  "fluidlite",
  "fraxswap",
  "fraxswap_v2",
  "gmx",
  "gmx_v1",
  "hydrex",
  "hyperblast",
  "infusion",
  "inkyswap",
  "integral",
  "iziswap",
  "kim",
  "kim_v2",
  "kim_v4",
  "kinetix",
  "lido",
  "lynex",
  "maker_psm",
  "maverick",
  "maverick_v2",
  "mdex",
  "meshswap",
  "metavault",
  "metavault_v2",
  "metavault_v3",
  "mimswap",
  "monoswap",
  "monoswap_v3",
  "morphex",
  "nile",
  "nile_v2",
  "nomiswap_stable",
  "nuri_cl",
  "origin",
  "orion",
  "orion_v2",
  "overnight",
  "pancakeswap",
  "pancakeswap_stable",
  "pancakeswap_v2",
  "pancakeswap_v3",
  "pinto",
  "polycat",
  "polygon_migration",
  "quickswap",
  "quickswap_v2",
  "quickswap_v3",
  "quickswap_v4",
  "ramses",
  "ramses_v2",
  "reservoir",
  "reservoir_v3",
  "retro",
  "ringswap",
  "rocketpool",
  "rocketswap",
  "roguex",
  "roguex_v1",
  "roguex_v2",
  "secta",
  "secta_v2",
  "secta_v3",
  "sharkswap",
  "sharkswap_v2",
  "shibaswap",
  "sky_migration",
  "skydrome",
  "solidly",
  "solidly_v3",
  "soswap",
  "spark",
  "spark_psm",
  "spartadex",
  "squadswap",
  "squadswap_v2",
  "squadswap_v3",
  "squidswap",
  "stepn",
  "supswap",
  "supswap_v2",
  "supswap_v3",
  "sushiswap",
  "sushiswap_v3",
  "swaap",
  "swaap_v2",
  "swapbased",
  "swapbased_v3",
  "swapblast",
  "swapblast_v2",
  "swapmode",
  "swapmode_v2",
  "swapmode_v3",
  "swapr",
  "synapse",
  "syncswap",
  "synthswap",
  "synthswap_v2",
  "synthswap_v3",
  "thena",
  "thick",
  "thruster",
  "thruster_v2_100",
  "thruster_v2_30",
  "thruster_v3",
  "tokan",
  "traderjoe",
  "traderjoe_v2.1",
  "traderjoe_v2.2",
  "treble",
  "treble_v2",
  "uniswap",
  "uniswap_v2",
  "uniswap_v3",
  "uniswap_v4",
  "velodrome",
  "velodrome_v2",
  "velodrome_v2_mode",
  "velodrome_v3",
  "waultswap",
  "wombat",
  "woofi",
  "woofi_v2",
  "worldswap",
  "worldswap_v2",
  "wrapped_blt",
  "xfai",
  "yearn",
  "yearn_v3",
  "z_protocol",
  "zebra",
  "zebra_v2",
] as const;
