export const SpokePoolAbi = [
  { inputs: [], name: "ClaimedMerkleLeaf", type: "error" },
  { inputs: [], name: "DepositsArePaused", type: "error" },
  { inputs: [], name: "DisabledRoute", type: "error" },
  { inputs: [], name: "ExpiredFillDeadline", type: "error" },
  { inputs: [], name: "FillsArePaused", type: "error" },
  {
    inputs: [],
    name: "InsufficientSpokePoolBalanceToExecuteLeaf",
    type: "error",
  },
  { inputs: [], name: "InvalidBytes32", type: "error" },
  { inputs: [], name: "InvalidChainId", type: "error" },
  { inputs: [], name: "InvalidCrossDomainAdmin", type: "error" },
  { inputs: [], name: "InvalidDepositorSignature", type: "error" },
  { inputs: [], name: "InvalidExclusiveRelayer", type: "error" },
  { inputs: [], name: "InvalidFillDeadline", type: "error" },
  { inputs: [], name: "InvalidMerkleLeaf", type: "error" },
  { inputs: [], name: "InvalidMerkleProof", type: "error" },
  { inputs: [], name: "InvalidPayoutAdjustmentPct", type: "error" },
  { inputs: [], name: "InvalidQuoteTimestamp", type: "error" },
  { inputs: [], name: "InvalidRelayerFeePct", type: "error" },
  { inputs: [], name: "InvalidSlowFillRequest", type: "error" },
  { inputs: [], name: "InvalidWithdrawalRecipient", type: "error" },
  {
    inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
    name: "LowLevelCallFailed",
    type: "error",
  },
  { inputs: [], name: "MaxTransferSizeExceeded", type: "error" },
  { inputs: [], name: "MsgValueDoesNotMatchInputAmount", type: "error" },
  { inputs: [], name: "NoRelayerRefundToClaim", type: "error" },
  { inputs: [], name: "NoSlowFillsInExclusivityWindow", type: "error" },
  { inputs: [], name: "NotCrossChainCall", type: "error" },
  { inputs: [], name: "NotCrossDomainAdmin", type: "error" },
  { inputs: [], name: "NotEOA", type: "error" },
  { inputs: [], name: "NotExclusiveRelayer", type: "error" },
  { inputs: [], name: "RelayFilled", type: "error" },
  { inputs: [], name: "WrongERC7683OrderId", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "inputToken",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "outputToken",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "inputAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "repaymentChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "originChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "depositId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "fillDeadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "exclusivityDeadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "exclusiveRelayer",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "relayer",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "depositor",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "recipient",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "messageHash",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "updatedRecipient",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "updatedMessageHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "updatedOutputAmount",
            type: "uint256",
          },
          {
            internalType: "enum V3SpokePoolInterface.FillType",
            name: "fillType",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct V3SpokePoolInterface.V3RelayExecutionEventInfo",
        name: "relayExecutionInfo",
        type: "tuple",
      },
    ],
    name: "FilledRelay",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "inputToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "outputToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "inputAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "repaymentChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "originChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "depositId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "fillDeadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "exclusivityDeadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "exclusiveRelayer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "relayer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "depositor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      { indexed: false, internalType: "bytes", name: "message", type: "bytes" },
      {
        components: [
          {
            internalType: "address",
            name: "updatedRecipient",
            type: "address",
          },
          { internalType: "bytes", name: "updatedMessage", type: "bytes" },
          {
            internalType: "uint256",
            name: "updatedOutputAmount",
            type: "uint256",
          },
          {
            internalType: "enum V3SpokePoolInterface.FillType",
            name: "fillType",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType:
          "struct V3SpokePoolInterface.LegacyV3RelayExecutionEventInfo",
        name: "relayExecutionInfo",
        type: "tuple",
      },
    ],
    name: "FilledV3Relay",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "inputToken",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "outputToken",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "inputAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "destinationChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "depositId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "quoteTimestamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "fillDeadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "exclusivityDeadline",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "depositor",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "recipient",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "exclusiveRelayer",
        type: "bytes32",
      },
      { indexed: false, internalType: "bytes", name: "message", type: "bytes" },
    ],
    name: "FundsDeposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "updatedOutputAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "depositId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "depositor",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "updatedRecipient",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "updatedMessage",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "depositorSignature",
        type: "bytes",
      },
    ],
    name: "RequestedSpeedUpDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "updatedOutputAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "depositId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "depositor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "updatedRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "updatedMessage",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "depositorSignature",
        type: "bytes",
      },
    ],
    name: "RequestedSpeedUpV3Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "inputToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "outputToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "inputAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "destinationChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "depositId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "quoteTimestamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "fillDeadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "exclusivityDeadline",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "depositor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "exclusiveRelayer",
        type: "address",
      },
      { indexed: false, internalType: "bytes", name: "message", type: "bytes" },
    ],
    name: "V3FundsDeposited",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "depositor", type: "bytes32" },
      { internalType: "bytes32", name: "recipient", type: "bytes32" },
      { internalType: "bytes32", name: "inputToken", type: "bytes32" },
      { internalType: "bytes32", name: "outputToken", type: "bytes32" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
      { internalType: "uint256", name: "destinationChainId", type: "uint256" },
      { internalType: "bytes32", name: "exclusiveRelayer", type: "bytes32" },
      { internalType: "uint32", name: "quoteTimestamp", type: "uint32" },
      { internalType: "uint32", name: "fillDeadline", type: "uint32" },
      { internalType: "uint32", name: "exclusivityParameter", type: "uint32" },
      { internalType: "bytes", name: "message", type: "bytes" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "address", name: "originToken", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "destinationChainId", type: "uint256" },
      { internalType: "int64", name: "relayerFeePct", type: "int64" },
      { internalType: "uint32", name: "quoteTimestamp", type: "uint32" },
      { internalType: "bytes", name: "message", type: "bytes" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "depositFor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "depositor", type: "bytes32" },
      { internalType: "bytes32", name: "recipient", type: "bytes32" },
      { internalType: "bytes32", name: "inputToken", type: "bytes32" },
      { internalType: "bytes32", name: "outputToken", type: "bytes32" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
      { internalType: "uint256", name: "destinationChainId", type: "uint256" },
      { internalType: "bytes32", name: "exclusiveRelayer", type: "bytes32" },
      { internalType: "uint32", name: "fillDeadlineOffset", type: "uint32" },
      { internalType: "uint32", name: "exclusivityParameter", type: "uint32" },
      { internalType: "bytes", name: "message", type: "bytes" },
    ],
    name: "depositNow",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "address", name: "inputToken", type: "address" },
      { internalType: "address", name: "outputToken", type: "address" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
      { internalType: "uint256", name: "destinationChainId", type: "uint256" },
      { internalType: "address", name: "exclusiveRelayer", type: "address" },
      { internalType: "uint32", name: "quoteTimestamp", type: "uint32" },
      { internalType: "uint32", name: "fillDeadline", type: "uint32" },
      { internalType: "uint32", name: "exclusivityParameter", type: "uint32" },
      { internalType: "bytes", name: "message", type: "bytes" },
    ],
    name: "depositV3",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "address", name: "inputToken", type: "address" },
      { internalType: "address", name: "outputToken", type: "address" },
      { internalType: "uint256", name: "inputAmount", type: "uint256" },
      { internalType: "uint256", name: "outputAmount", type: "uint256" },
      { internalType: "uint256", name: "destinationChainId", type: "uint256" },
      { internalType: "address", name: "exclusiveRelayer", type: "address" },
      { internalType: "uint32", name: "fillDeadlineOffset", type: "uint32" },
      { internalType: "uint32", name: "exclusivityParameter", type: "uint32" },
      { internalType: "bytes", name: "message", type: "bytes" },
    ],
    name: "depositV3Now",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "orderId", type: "bytes32" },
      { internalType: "bytes", name: "originData", type: "bytes" },
      { internalType: "bytes", name: "fillerData", type: "bytes" },
    ],
    name: "fill",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "depositor", type: "bytes32" },
          { internalType: "bytes32", name: "recipient", type: "bytes32" },
          {
            internalType: "bytes32",
            name: "exclusiveRelayer",
            type: "bytes32",
          },
          { internalType: "bytes32", name: "inputToken", type: "bytes32" },
          { internalType: "bytes32", name: "outputToken", type: "bytes32" },
          { internalType: "uint256", name: "inputAmount", type: "uint256" },
          { internalType: "uint256", name: "outputAmount", type: "uint256" },
          { internalType: "uint256", name: "originChainId", type: "uint256" },
          { internalType: "uint256", name: "depositId", type: "uint256" },
          { internalType: "uint32", name: "fillDeadline", type: "uint32" },
          {
            internalType: "uint32",
            name: "exclusivityDeadline",
            type: "uint32",
          },
          { internalType: "bytes", name: "message", type: "bytes" },
        ],
        internalType: "struct V3SpokePoolInterface.V3RelayData",
        name: "relayData",
        type: "tuple",
      },
      { internalType: "uint256", name: "repaymentChainId", type: "uint256" },
      { internalType: "bytes32", name: "repaymentAddress", type: "bytes32" },
    ],
    name: "fillRelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "depositor", type: "bytes32" },
          { internalType: "bytes32", name: "recipient", type: "bytes32" },
          {
            internalType: "bytes32",
            name: "exclusiveRelayer",
            type: "bytes32",
          },
          { internalType: "bytes32", name: "inputToken", type: "bytes32" },
          { internalType: "bytes32", name: "outputToken", type: "bytes32" },
          { internalType: "uint256", name: "inputAmount", type: "uint256" },
          { internalType: "uint256", name: "outputAmount", type: "uint256" },
          { internalType: "uint256", name: "originChainId", type: "uint256" },
          { internalType: "uint256", name: "depositId", type: "uint256" },
          { internalType: "uint32", name: "fillDeadline", type: "uint32" },
          {
            internalType: "uint32",
            name: "exclusivityDeadline",
            type: "uint32",
          },
          { internalType: "bytes", name: "message", type: "bytes" },
        ],
        internalType: "struct V3SpokePoolInterface.V3RelayData",
        name: "relayData",
        type: "tuple",
      },
      { internalType: "uint256", name: "repaymentChainId", type: "uint256" },
      { internalType: "bytes32", name: "repaymentAddress", type: "bytes32" },
      { internalType: "uint256", name: "updatedOutputAmount", type: "uint256" },
      { internalType: "bytes32", name: "updatedRecipient", type: "bytes32" },
      { internalType: "bytes", name: "updatedMessage", type: "bytes" },
      { internalType: "bytes", name: "depositorSignature", type: "bytes" },
    ],
    name: "fillRelayWithUpdatedDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "fillStatuses",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "depositor", type: "address" },
          { internalType: "address", name: "recipient", type: "address" },
          {
            internalType: "address",
            name: "exclusiveRelayer",
            type: "address",
          },
          { internalType: "address", name: "inputToken", type: "address" },
          { internalType: "address", name: "outputToken", type: "address" },
          { internalType: "uint256", name: "inputAmount", type: "uint256" },
          { internalType: "uint256", name: "outputAmount", type: "uint256" },
          { internalType: "uint256", name: "originChainId", type: "uint256" },
          { internalType: "uint32", name: "depositId", type: "uint32" },
          { internalType: "uint32", name: "fillDeadline", type: "uint32" },
          {
            internalType: "uint32",
            name: "exclusivityDeadline",
            type: "uint32",
          },
          { internalType: "bytes", name: "message", type: "bytes" },
        ],
        internalType: "struct V3SpokePoolInterface.V3RelayDataLegacy",
        name: "relayData",
        type: "tuple",
      },
      { internalType: "uint256", name: "repaymentChainId", type: "uint256" },
    ],
    name: "fillV3Relay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "depositor", type: "bytes32" },
          { internalType: "bytes32", name: "recipient", type: "bytes32" },
          {
            internalType: "bytes32",
            name: "exclusiveRelayer",
            type: "bytes32",
          },
          { internalType: "bytes32", name: "inputToken", type: "bytes32" },
          { internalType: "bytes32", name: "outputToken", type: "bytes32" },
          { internalType: "uint256", name: "inputAmount", type: "uint256" },
          { internalType: "uint256", name: "outputAmount", type: "uint256" },
          { internalType: "uint256", name: "originChainId", type: "uint256" },
          { internalType: "uint256", name: "depositId", type: "uint256" },
          { internalType: "uint32", name: "fillDeadline", type: "uint32" },
          {
            internalType: "uint32",
            name: "exclusivityDeadline",
            type: "uint32",
          },
          { internalType: "bytes", name: "message", type: "bytes" },
        ],
        internalType: "struct V3SpokePoolInterface.V3RelayData",
        name: "relayData",
        type: "tuple",
      },
    ],
    name: "getV3RelayHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "depositor", type: "bytes32" },
      { internalType: "uint256", name: "depositId", type: "uint256" },
      { internalType: "uint256", name: "updatedOutputAmount", type: "uint256" },
      { internalType: "bytes32", name: "updatedRecipient", type: "bytes32" },
      { internalType: "bytes", name: "updatedMessage", type: "bytes" },
      { internalType: "bytes", name: "depositorSignature", type: "bytes" },
    ],
    name: "speedUpDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "uint256", name: "depositId", type: "uint256" },
      { internalType: "uint256", name: "updatedOutputAmount", type: "uint256" },
      { internalType: "address", name: "updatedRecipient", type: "address" },
      { internalType: "bytes", name: "updatedMessage", type: "bytes" },
      { internalType: "bytes", name: "depositorSignature", type: "bytes" },
    ],
    name: "speedUpV3Deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
