// Auto-generated file. Do not edit manually.
// Generated on 2026-01-28T10:12:52.997Z
// This file contains available liquidity sources for LiFi DEX integration

export const SOURCES = {
  strategy: "lifi",
  sources: {
    "1": [
      { key: "dodo", names: ["dodo"] },
      { key: "gluex", names: ["gluex"] },
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "merkle", names: ["merkle"] },
      { key: "fly", names: ["fly"] },
    ],
    "10": [
      { key: "dodo", names: ["dodo"] },
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "56": [
      { key: "dodo", names: ["dodo"] },
      { key: "eisen", names: ["eisen"] },
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "130": [
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "1inch", names: ["1inch"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "137": [
      { key: "dodo", names: ["dodo"] },
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
    ],
    "143": [
      { key: "eisen", names: ["eisen"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "oogaboogameta", names: ["oogaboogameta"] },
      { key: "fly", names: ["fly"] },
      { key: "monorail", names: ["monorail"] },
      { key: "kuru", names: ["kuru"] },
    ],
    "232": [{ key: "lifidexaggregator", names: ["lifidexaggregator"] }],
    "288": [
      { key: "lifidexaggregator", names: ["lifidexaggregator"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "324": [
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
    ],
    "480": [{ key: "lifidexaggregator", names: ["lifidexaggregator"] }],
    "999": [
      { key: "eisen", names: ["eisen"] },
      { key: "gluex", names: ["gluex"] },
      { key: "enso", names: ["enso"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "bebop", names: ["bebop"] },
      { key: "liquidswap", names: ["liquidswap"] },
      { key: "hyperbloom", names: ["hyperbloom"] },
      { key: "hypertrade", names: ["hypertrade"] },
      { key: "oogaboogameta", names: ["oogaboogameta"] },
      { key: "hyperflow", names: ["hyperflow"] },
      { key: "fly", names: ["fly"] },
    ],
    "1135": [{ key: "lifidexaggregator", names: ["lifidexaggregator"] }],
    "1337": [{ key: "hyperliquidSpotDex", names: ["hyperliquidSpotDex"] }],
    "1868": [
      { key: "eisen", names: ["eisen"] },
      { key: "enso", names: ["enso"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "8453": [
      { key: "eisen", names: ["eisen"] },
      { key: "gluex", names: ["gluex"] },
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "merkle", names: ["merkle"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "9745": [
      { key: "gluex", names: ["gluex"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
    ],
    "34443": [
      { key: "eisen", names: ["eisen"] },
      { key: "odos", names: ["odos"] },
      { key: "openocean", names: ["openocean"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "42161": [
      { key: "dodo", names: ["dodo"] },
      { key: "eisen", names: ["eisen"] },
      { key: "paraswap", names: ["paraswap"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "57073": [
      { key: "enso", names: ["enso"] },
      { key: "lifidexaggregator", names: ["lifidexaggregator"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "59144": [
      { key: "eisen", names: ["eisen"] },
      { key: "enso", names: ["enso"] },
      { key: "odos", names: ["odos"] },
      { key: "1inch", names: ["1inch"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
    "60808": [{ key: "lifidexaggregator", names: ["lifidexaggregator"] }],
    "81457": [
      { key: "eisen", names: ["eisen"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
    ],
    "534352": [
      { key: "eisen", names: ["eisen"] },
      { key: "odos", names: ["odos"] },
      { key: "openocean", names: ["openocean"] },
      { key: "kyberswap", names: ["kyberswap"] },
      { key: "sushiswap", names: ["sushiswap"] },
      { key: "okx", names: ["okx"] },
      { key: "fly", names: ["fly"] },
      { key: "nordstern", names: ["nordstern"] },
    ],
  },
} as {
  strategy: string;
  sources: {
    [chainId: number]: {
      key: string; // Source key used by the DEX API
      names: string[]; // Source names that match the key
    }[];
  };
};

export const ALL_SOURCES = [
  "1inch",
  "bebop",
  "dodo",
  "eisen",
  "enso",
  "fly",
  "gluex",
  "hyperbloom",
  "hyperflow",
  "hyperliquidSpotDex",
  "hypertrade",
  "kuru",
  "kyberswap",
  "lifidexaggregator",
  "liquidswap",
  "merkle",
  "monorail",
  "nordstern",
  "odos",
  "okx",
  "oogaboogameta",
  "openocean",
  "paraswap",
  "sushiswap",
] as const;
