import { TOKEN_SYMBOLS_MAP } from "../../../_constants";
import { CHAIN_IDs } from "../../../_constants";

export const USDH_FILL_DESTINATION_GAS_LIMIT_USD = 0.25; // 0.25 USD

export const HYPERLIQUID_DEPOSIT_HANDLER_ADDRESS =
  "0xb4aead497fcbeaa3c37919032d42c29682f46376";

export const SUPPORTED_INPUT_TOKENS = [TOKEN_SYMBOLS_MAP.USDC];
export const SUPPORTED_OUTPUT_TOKENS = [
  TOKEN_SYMBOLS_MAP.USDH,
  TOKEN_SYMBOLS_MAP["USDH-SPOT"],
];
export const SUPPORTED_DESTINATION_CHAINS = [
  CHAIN_IDs.HYPEREVM,
  CHAIN_IDs.HYPERCORE,
  CHAIN_IDs.HYPEREVM_TESTNET,
  CHAIN_IDs.HYPERCORE_TESTNET,
];

export const BRIDGEABLE_OUTPUT_TOKEN_PER_OUTPUT_TOKEN: Record<
  (typeof SUPPORTED_OUTPUT_TOKENS)[number]["symbol"],
  (typeof TOKEN_SYMBOLS_MAP)[keyof typeof TOKEN_SYMBOLS_MAP]
> = {
  USDH: TOKEN_SYMBOLS_MAP.USDH,
  "USDH-SPOT": TOKEN_SYMBOLS_MAP.USDH,
};

export const ERROR_MESSAGE_PREFIX = "Sponsored Intent";
