/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "@across-protocol/contracts/dist/typechain/common";

export declare namespace SpokePoolV3Periphery {
  export type DepositDataStruct = {
    outputToken: string;
    outputAmount: BigNumberish;
    depositor: string;
    recipient: string;
    destinationChainid: BigNumberish;
    exclusiveRelayer: string;
    quoteTimestamp: BigNumberish;
    fillDeadline: BigNumberish;
    exclusivityParameter: BigNumberish;
    message: BytesLike;
  };

  export type DepositDataStructOutput = [
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    number,
    number,
    number,
    string,
  ] & {
    outputToken: string;
    outputAmount: BigNumber;
    depositor: string;
    recipient: string;
    destinationChainid: BigNumber;
    exclusiveRelayer: string;
    quoteTimestamp: number;
    fillDeadline: number;
    exclusivityParameter: number;
    message: string;
  };
}

export interface SpokePoolV3PeripheryInterface extends utils.Interface {
  functions: {
    "allowedSelectors(bytes4)": FunctionFragment;
    "deposit(address,address,uint256,uint256,uint256,address,uint32,uint32,uint32,bytes)": FunctionFragment;
    "depositWithAuthorization(address,uint256,(address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256,uint256,bytes32,uint8,bytes32,bytes32)": FunctionFragment;
    "depositWithPermit(address,uint256,(address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "exchange()": FunctionFragment;
    "initialize(address,address,address)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "spokePool()": FunctionFragment;
    "swapAndBridge(address,address,bytes,uint256,uint256,(address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes))": FunctionFragment;
    "swapAndBridgeWithAuthorization(address,address,bytes,uint256,uint256,(address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256,uint256,bytes32,uint8,bytes32,bytes32)": FunctionFragment;
    "swapAndBridgeWithPermit(address,address,bytes,uint256,uint256,(address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256,uint8,bytes32,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allowedSelectors"
      | "deposit"
      | "depositWithAuthorization"
      | "depositWithPermit"
      | "exchange"
      | "initialize"
      | "multicall"
      | "spokePool"
      | "swapAndBridge"
      | "swapAndBridgeWithAuthorization"
      | "swapAndBridgeWithPermit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowedSelectors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithAuthorization",
    values: [
      string,
      BigNumberish,
      SpokePoolV3Periphery.DepositDataStruct,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithPermit",
    values: [
      string,
      BigNumberish,
      SpokePoolV3Periphery.DepositDataStruct,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(functionFragment: "exchange", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "spokePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapAndBridge",
    values: [
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      SpokePoolV3Periphery.DepositDataStruct,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndBridgeWithAuthorization",
    values: [
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      SpokePoolV3Periphery.DepositDataStruct,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndBridgeWithPermit",
    values: [
      string,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      SpokePoolV3Periphery.DepositDataStruct,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowedSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exchange", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spokePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridgeWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridgeWithPermit",
    data: BytesLike
  ): Result;

  events: {
    "SwapBeforeBridge(address,address,address,uint256,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapBeforeBridge"): EventFragment;
}

export interface SwapBeforeBridgeEventObject {
  exchange: string;
  swapToken: string;
  acrossInputToken: string;
  swapTokenAmount: BigNumber;
  acrossInputAmount: BigNumber;
  acrossOutputToken: string;
  acrossOutputAmount: BigNumber;
}
export type SwapBeforeBridgeEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string, BigNumber],
  SwapBeforeBridgeEventObject
>;

export type SwapBeforeBridgeEventFilter =
  TypedEventFilter<SwapBeforeBridgeEvent>;

export interface SpokePoolV3Periphery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpokePoolV3PeripheryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allowedSelectors(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositWithAuthorization(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositWithPermit(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    exchange(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _exchange: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    spokePool(overrides?: CallOverrides): Promise<[string]>;

    swapAndBridge(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    swapAndBridgeWithAuthorization(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    swapAndBridgeWithPermit(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  allowedSelectors(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deposit(
    recipient: string,
    inputToken: string,
    inputAmount: BigNumberish,
    outputAmount: BigNumberish,
    destinationChainId: BigNumberish,
    exclusiveRelayer: string,
    quoteTimestamp: BigNumberish,
    fillDeadline: BigNumberish,
    exclusivityParameter: BigNumberish,
    message: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositWithAuthorization(
    acrossInputToken: string,
    acrossInputAmount: BigNumberish,
    depositData: SpokePoolV3Periphery.DepositDataStruct,
    validAfter: BigNumberish,
    validBefore: BigNumberish,
    nonce: BytesLike,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositWithPermit(
    acrossInputToken: string,
    acrossInputAmount: BigNumberish,
    depositData: SpokePoolV3Periphery.DepositDataStruct,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  exchange(overrides?: CallOverrides): Promise<string>;

  initialize(
    _spokePool: string,
    _wrappedNativeToken: string,
    _exchange: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  multicall(
    data: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  spokePool(overrides?: CallOverrides): Promise<string>;

  swapAndBridge(
    swapToken: string,
    acrossInputToken: string,
    routerCalldata: BytesLike,
    swapTokenAmount: BigNumberish,
    minExpectedInputTokenAmount: BigNumberish,
    depositData: SpokePoolV3Periphery.DepositDataStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  swapAndBridgeWithAuthorization(
    swapToken: string,
    acrossInputToken: string,
    routerCalldata: BytesLike,
    swapTokenAmount: BigNumberish,
    minExpectedInputTokenAmount: BigNumberish,
    depositData: SpokePoolV3Periphery.DepositDataStruct,
    validAfter: BigNumberish,
    validBefore: BigNumberish,
    nonce: BytesLike,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  swapAndBridgeWithPermit(
    swapToken: string,
    acrossInputToken: string,
    routerCalldata: BytesLike,
    swapTokenAmount: BigNumberish,
    minExpectedInputTokenAmount: BigNumberish,
    depositData: SpokePoolV3Periphery.DepositDataStruct,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowedSelectors(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithAuthorization(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithPermit(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    exchange(overrides?: CallOverrides): Promise<string>;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _exchange: string,
      overrides?: CallOverrides
    ): Promise<void>;

    multicall(data: BytesLike[], overrides?: CallOverrides): Promise<string[]>;

    spokePool(overrides?: CallOverrides): Promise<string>;

    swapAndBridge(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndBridgeWithAuthorization(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndBridgeWithPermit(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SwapBeforeBridge(address,address,address,uint256,uint256,address,uint256)"(
      exchange?: null,
      swapToken?: string | null,
      acrossInputToken?: string | null,
      swapTokenAmount?: null,
      acrossInputAmount?: null,
      acrossOutputToken?: string | null,
      acrossOutputAmount?: null
    ): SwapBeforeBridgeEventFilter;
    SwapBeforeBridge(
      exchange?: null,
      swapToken?: string | null,
      acrossInputToken?: string | null,
      swapTokenAmount?: null,
      acrossInputAmount?: null,
      acrossOutputToken?: string | null,
      acrossOutputAmount?: null
    ): SwapBeforeBridgeEventFilter;
  };

  estimateGas: {
    allowedSelectors(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    depositWithAuthorization(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositWithPermit(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    exchange(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _exchange: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    spokePool(overrides?: CallOverrides): Promise<BigNumber>;

    swapAndBridge(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    swapAndBridgeWithAuthorization(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    swapAndBridgeWithPermit(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowedSelectors(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositWithAuthorization(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositWithPermit(
      acrossInputToken: string,
      acrossInputAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    exchange(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _exchange: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    spokePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapAndBridge(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    swapAndBridgeWithAuthorization(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    swapAndBridgeWithPermit(
      swapToken: string,
      acrossInputToken: string,
      routerCalldata: BytesLike,
      swapTokenAmount: BigNumberish,
      minExpectedInputTokenAmount: BigNumberish,
      depositData: SpokePoolV3Periphery.DepositDataStruct,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
