/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "@across-protocol/contracts/dist/typechain/common";

export declare namespace SpokePoolV3PeripheryInterface {
  export type FeesStruct = { amount: BigNumberish; recipient: string };

  export type FeesStructOutput = [BigNumber, string] & {
    amount: BigNumber;
    recipient: string;
  };

  export type BaseDepositDataStruct = {
    inputToken: string;
    outputToken: string;
    outputAmount: BigNumberish;
    depositor: string;
    recipient: string;
    destinationChainId: BigNumberish;
    exclusiveRelayer: string;
    quoteTimestamp: BigNumberish;
    fillDeadline: BigNumberish;
    exclusivityParameter: BigNumberish;
    message: BytesLike;
  };

  export type BaseDepositDataStructOutput = [
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    number,
    number,
    number,
    string,
  ] & {
    inputToken: string;
    outputToken: string;
    outputAmount: BigNumber;
    depositor: string;
    recipient: string;
    destinationChainId: BigNumber;
    exclusiveRelayer: string;
    quoteTimestamp: number;
    fillDeadline: number;
    exclusivityParameter: number;
    message: string;
  };

  export type DepositDataStruct = {
    submissionFees: SpokePoolV3PeripheryInterface.FeesStruct;
    baseDepositData: SpokePoolV3PeripheryInterface.BaseDepositDataStruct;
    inputAmount: BigNumberish;
  };

  export type DepositDataStructOutput = [
    SpokePoolV3PeripheryInterface.FeesStructOutput,
    SpokePoolV3PeripheryInterface.BaseDepositDataStructOutput,
    BigNumber,
  ] & {
    submissionFees: SpokePoolV3PeripheryInterface.FeesStructOutput;
    baseDepositData: SpokePoolV3PeripheryInterface.BaseDepositDataStructOutput;
    inputAmount: BigNumber;
  };

  export type SwapAndDepositDataStruct = {
    submissionFees: SpokePoolV3PeripheryInterface.FeesStruct;
    depositData: SpokePoolV3PeripheryInterface.BaseDepositDataStruct;
    swapToken: string;
    exchange: string;
    transferType: BigNumberish;
    swapTokenAmount: BigNumberish;
    minExpectedInputTokenAmount: BigNumberish;
    routerCalldata: BytesLike;
  };

  export type SwapAndDepositDataStructOutput = [
    SpokePoolV3PeripheryInterface.FeesStructOutput,
    SpokePoolV3PeripheryInterface.BaseDepositDataStructOutput,
    string,
    string,
    number,
    BigNumber,
    BigNumber,
    string,
  ] & {
    submissionFees: SpokePoolV3PeripheryInterface.FeesStructOutput;
    depositData: SpokePoolV3PeripheryInterface.BaseDepositDataStructOutput;
    swapToken: string;
    exchange: string;
    transferType: number;
    swapTokenAmount: BigNumber;
    minExpectedInputTokenAmount: BigNumber;
    routerCalldata: string;
  };
}

export declare namespace IPermit2 {
  export type TokenPermissionsStruct = { token: string; amount: BigNumberish };

  export type TokenPermissionsStructOutput = [string, BigNumber] & {
    token: string;
    amount: BigNumber;
  };

  export type PermitTransferFromStruct = {
    permitted: IPermit2.TokenPermissionsStruct;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type PermitTransferFromStructOutput = [
    IPermit2.TokenPermissionsStructOutput,
    BigNumber,
    BigNumber,
  ] & {
    permitted: IPermit2.TokenPermissionsStructOutput;
    nonce: BigNumber;
    deadline: BigNumber;
  };
}

export interface SpokePoolV3PeripheryInterface extends utils.Interface {
  functions: {
    "deposit(address,address,uint256,uint256,uint256,address,uint32,uint32,uint32,bytes)": FunctionFragment;
    "depositWithAuthorization(address,((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256),uint256,uint256,bytes32,bytes,bytes)": FunctionFragment;
    "depositWithPermit(address,((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256),uint256,bytes,bytes)": FunctionFragment;
    "depositWithPermit2(address,((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),uint256),((address,uint256),uint256,uint256),bytes)": FunctionFragment;
    "domainSeparator()": FunctionFragment;
    "eip712Domain()": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "isValidSignature(bytes32,bytes)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "permit2()": FunctionFragment;
    "proxy()": FunctionFragment;
    "spokePool()": FunctionFragment;
    "swapAndBridge(((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),address,address,uint8,uint256,uint256,bytes))": FunctionFragment;
    "swapAndBridgeWithAuthorization(address,((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),address,address,uint8,uint256,uint256,bytes),uint256,uint256,bytes32,bytes,bytes)": FunctionFragment;
    "swapAndBridgeWithPermit(address,((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),address,address,uint8,uint256,uint256,bytes),uint256,bytes,bytes)": FunctionFragment;
    "swapAndBridgeWithPermit2(address,((uint256,address),(address,address,uint256,address,address,uint256,address,uint32,uint32,uint32,bytes),address,address,uint8,uint256,uint256,bytes),((address,uint256),uint256,uint256),bytes)": FunctionFragment;
    "wrappedNativeToken()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deposit"
      | "depositWithAuthorization"
      | "depositWithPermit"
      | "depositWithPermit2"
      | "domainSeparator"
      | "eip712Domain"
      | "initialize"
      | "isValidSignature"
      | "multicall"
      | "permit2"
      | "proxy"
      | "spokePool"
      | "swapAndBridge"
      | "swapAndBridgeWithAuthorization"
      | "swapAndBridgeWithPermit"
      | "swapAndBridgeWithPermit2"
      | "wrappedNativeToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithAuthorization",
    values: [
      string,
      SpokePoolV3PeripheryInterface.DepositDataStruct,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithPermit",
    values: [
      string,
      SpokePoolV3PeripheryInterface.DepositDataStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithPermit2",
    values: [
      string,
      SpokePoolV3PeripheryInterface.DepositDataStruct,
      IPermit2.PermitTransferFromStruct,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;
  encodeFunctionData(functionFragment: "proxy", values?: undefined): string;
  encodeFunctionData(functionFragment: "spokePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapAndBridge",
    values: [SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndBridgeWithAuthorization",
    values: [
      string,
      SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndBridgeWithPermit",
    values: [
      string,
      SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndBridgeWithPermit2",
    values: [
      string,
      SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      IPermit2.PermitTransferFromStruct,
      BytesLike,
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedNativeToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithPermit2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proxy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spokePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridgeWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridgeWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridgeWithPermit2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedNativeToken",
    data: BytesLike
  ): Result;

  events: {
    "EIP712DomainChanged()": EventFragment;
    "SwapBeforeBridge(address,bytes,address,address,uint256,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapBeforeBridge"): EventFragment;
}

export interface EIP712DomainChangedEventObject {}
export type EIP712DomainChangedEvent = TypedEvent<
  [],
  EIP712DomainChangedEventObject
>;

export type EIP712DomainChangedEventFilter =
  TypedEventFilter<EIP712DomainChangedEvent>;

export interface SwapBeforeBridgeEventObject {
  exchange: string;
  exchangeCalldata: string;
  swapToken: string;
  acrossInputToken: string;
  swapTokenAmount: BigNumber;
  acrossInputAmount: BigNumber;
  acrossOutputToken: string;
  acrossOutputAmount: BigNumber;
}
export type SwapBeforeBridgeEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber, string, BigNumber],
  SwapBeforeBridgeEventObject
>;

export type SwapBeforeBridgeEventFilter =
  TypedEventFilter<SwapBeforeBridgeEvent>;

export interface SpokePoolV3Periphery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpokePoolV3PeripheryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositWithAuthorization(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositWithPermit(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositWithPermit2(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    domainSeparator(overrides?: CallOverrides): Promise<[string]>;

    eip712Domain(overrides?: CallOverrides): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _proxy: string,
      _permit2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isValidSignature(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { magicBytes: string }>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    permit2(overrides?: CallOverrides): Promise<[string]>;

    proxy(overrides?: CallOverrides): Promise<[string]>;

    spokePool(overrides?: CallOverrides): Promise<[string]>;

    swapAndBridge(
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    swapAndBridgeWithAuthorization(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    swapAndBridgeWithPermit(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    swapAndBridgeWithPermit2(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    wrappedNativeToken(overrides?: CallOverrides): Promise<[string]>;
  };

  deposit(
    recipient: string,
    inputToken: string,
    inputAmount: BigNumberish,
    outputAmount: BigNumberish,
    destinationChainId: BigNumberish,
    exclusiveRelayer: string,
    quoteTimestamp: BigNumberish,
    fillDeadline: BigNumberish,
    exclusivityParameter: BigNumberish,
    message: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositWithAuthorization(
    signatureOwner: string,
    depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
    validAfter: BigNumberish,
    validBefore: BigNumberish,
    nonce: BytesLike,
    receiveWithAuthSignature: BytesLike,
    depositDataSignature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositWithPermit(
    signatureOwner: string,
    depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
    deadline: BigNumberish,
    permitSignature: BytesLike,
    depositDataSignature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositWithPermit2(
    signatureOwner: string,
    depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
    permit: IPermit2.PermitTransferFromStruct,
    signature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  domainSeparator(overrides?: CallOverrides): Promise<string>;

  eip712Domain(overrides?: CallOverrides): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  initialize(
    _spokePool: string,
    _wrappedNativeToken: string,
    _proxy: string,
    _permit2: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isValidSignature(
    arg0: BytesLike,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  multicall(
    data: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  permit2(overrides?: CallOverrides): Promise<string>;

  proxy(overrides?: CallOverrides): Promise<string>;

  spokePool(overrides?: CallOverrides): Promise<string>;

  swapAndBridge(
    swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  swapAndBridgeWithAuthorization(
    signatureOwner: string,
    swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
    validAfter: BigNumberish,
    validBefore: BigNumberish,
    nonce: BytesLike,
    receiveWithAuthSignature: BytesLike,
    swapAndDepositDataSignature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  swapAndBridgeWithPermit(
    signatureOwner: string,
    swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
    deadline: BigNumberish,
    permitSignature: BytesLike,
    swapAndDepositDataSignature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  swapAndBridgeWithPermit2(
    signatureOwner: string,
    swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
    permit: IPermit2.PermitTransferFromStruct,
    signature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  wrappedNativeToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithAuthorization(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithPermit(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithPermit2(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    domainSeparator(overrides?: CallOverrides): Promise<string>;

    eip712Domain(overrides?: CallOverrides): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _proxy: string,
      _permit2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isValidSignature(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    multicall(data: BytesLike[], overrides?: CallOverrides): Promise<string[]>;

    permit2(overrides?: CallOverrides): Promise<string>;

    proxy(overrides?: CallOverrides): Promise<string>;

    spokePool(overrides?: CallOverrides): Promise<string>;

    swapAndBridge(
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndBridgeWithAuthorization(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndBridgeWithPermit(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndBridgeWithPermit2(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    wrappedNativeToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "EIP712DomainChanged()"(): EIP712DomainChangedEventFilter;
    EIP712DomainChanged(): EIP712DomainChangedEventFilter;

    "SwapBeforeBridge(address,bytes,address,address,uint256,uint256,address,uint256)"(
      exchange?: null,
      exchangeCalldata?: null,
      swapToken?: string | null,
      acrossInputToken?: string | null,
      swapTokenAmount?: null,
      acrossInputAmount?: null,
      acrossOutputToken?: string | null,
      acrossOutputAmount?: null
    ): SwapBeforeBridgeEventFilter;
    SwapBeforeBridge(
      exchange?: null,
      exchangeCalldata?: null,
      swapToken?: string | null,
      acrossInputToken?: string | null,
      swapTokenAmount?: null,
      acrossInputAmount?: null,
      acrossOutputToken?: string | null,
      acrossOutputAmount?: null
    ): SwapBeforeBridgeEventFilter;
  };

  estimateGas: {
    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    depositWithAuthorization(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositWithPermit(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositWithPermit2(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    domainSeparator(overrides?: CallOverrides): Promise<BigNumber>;

    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _proxy: string,
      _permit2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isValidSignature(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    permit2(overrides?: CallOverrides): Promise<BigNumber>;

    proxy(overrides?: CallOverrides): Promise<BigNumber>;

    spokePool(overrides?: CallOverrides): Promise<BigNumber>;

    swapAndBridge(
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    swapAndBridgeWithAuthorization(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    swapAndBridgeWithPermit(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    swapAndBridgeWithPermit2(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    wrappedNativeToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deposit(
      recipient: string,
      inputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityParameter: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositWithAuthorization(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositWithPermit(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      depositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositWithPermit2(
      signatureOwner: string,
      depositData: SpokePoolV3PeripheryInterface.DepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    domainSeparator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _spokePool: string,
      _wrappedNativeToken: string,
      _proxy: string,
      _permit2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      arg0: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    permit2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    spokePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapAndBridge(
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    swapAndBridgeWithAuthorization(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      receiveWithAuthSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    swapAndBridgeWithPermit(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      deadline: BigNumberish,
      permitSignature: BytesLike,
      swapAndDepositDataSignature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    swapAndBridgeWithPermit2(
      signatureOwner: string,
      swapAndDepositData: SpokePoolV3PeripheryInterface.SwapAndDepositDataStruct,
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    wrappedNativeToken(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
