// Auto-generated file. Do not edit manually.
// Generated on 2025-09-29T08:09:29.316Z
// This file contains available liquidity sources for Jupiter DEX integration

export const SOURCES = {
  strategy: "jupiter",
  sources: {
    "34268394551451": [
      { key: "OpenBook V2", names: ["openbook_v2", "openbook"] },
      { key: "StepN", names: ["stepn"] },
      {
        key: "Stabble Weighted Swap",
        names: ["stabble_weighted_swap", "stabble weighted swap"],
      },
      { key: "Cropper", names: ["cropper"] },
      { key: "Phoenix", names: ["phoenix"] },
      { key: "ZeroFi", names: ["zerofi"] },
      { key: "Perps", names: ["perps"] },
      { key: "Meteora DLMM", names: ["meteora_dlmm", "meteora dlmm"] },
      { key: "Woofi", names: ["woofi"] },
      { key: "Crema", names: ["crema"] },
      { key: "HumidiFi", names: ["humidifi"] },
      { key: "Meteora DAMM v2", names: ["meteora_damm_v2", "meteora damm"] },
      { key: "Raydium", names: ["raydium"] },
      { key: "Gavel", names: ["gavel"] },
      {
        key: "Raydium Launchlab",
        names: ["raydium_launchlab", "raydium launchlab"],
      },
      {
        key: "Sanctum Infinity",
        names: ["sanctum_infinity", "sanctum infinity"],
      },
      { key: "Aquifer", names: ["aquifer"] },
      { key: "Lifinity V2", names: ["lifinity_v2", "lifinity"] },
      { key: "1DEX", names: ["1dex"] },
      { key: "Solayer", names: ["solayer"] },
      {
        key: "Stabble Stable Swap",
        names: ["stabble_stable_swap", "stabble stable swap"],
      },
      { key: "Heaven", names: ["heaven"] },
      { key: "Perena", names: ["perena"] },
      { key: "TesseraV", names: ["tesserav"] },
      { key: "GoonFi", names: ["goonfi"] },
      { key: "GooseFX GAMMA", names: ["goosefx_gamma", "goosefx gamma"] },
      { key: "Sanctum", names: ["sanctum"] },
      { key: "Byreal", names: ["byreal"] },
      { key: "Bonkswap", names: ["bonkswap"] },
      { key: "SolFi V2", names: ["solfi_v2", "solfi"] },
      { key: "SolFi", names: ["solfi"] },
      { key: "Saros", names: ["saros"] },
      { key: "AlphaQ", names: ["alphaq"] },
      { key: "Guacswap", names: ["guacswap"] },
      { key: "Whirlpool", names: ["whirlpool"] },
      { key: "Saber", names: ["saber"] },
      {
        key: "Saber (Decimals)",
        names: ["saber_(decimals)", "saber (decimals)"],
      },
      { key: "Raydium CLMM", names: ["raydium_clmm", "raydium clmm"] },
      { key: "Moonit", names: ["moonit"] },
      { key: "Invariant", names: ["invariant"] },
      { key: "Orca V1", names: ["orca_v1", "orca"] },
      { key: "DefiTuna", names: ["defituna"] },
      { key: "FluxBeam", names: ["fluxbeam"] },
      { key: "Boop.fun", names: ["boop_fun", "boop.fun"] },
      { key: "Orca V2", names: ["orca_v2", "orca"] },
      { key: "Raydium CP", names: ["raydium_cp", "raydium cp"] },
      { key: "Token Swap", names: ["token_swap", "token swap"] },
      {
        key: "Dynamic Bonding Curve",
        names: ["dynamic_bonding_curve", "dynamic bonding curve"],
      },
      { key: "Helium Network", names: ["helium_network", "helium network"] },
      { key: "Mercurial", names: ["mercurial"] },
      { key: "Aldrin V2", names: ["aldrin_v2", "aldrin"] },
      { key: "PancakeSwap", names: ["pancakeswap"] },
      { key: "DexLab", names: ["dexlab"] },
      { key: "Penguin", names: ["penguin"] },
      { key: "Virtuals", names: ["virtuals"] },
      { key: "Obric V2", names: ["obric_v2", "obric"] },
      { key: "Pump.fun", names: ["pump_fun", "pump.fun"] },
      { key: "Aldrin", names: ["aldrin"] },
      { key: "Pump.fun Amm", names: ["pump_fun_amm", "pump.fun amm"] },
      { key: "Meteora", names: ["meteora"] },
    ],
  },
} as {
  strategy: string;
  sources: {
    [chainId: number]: {
      key: string; // Source key used by the DEX API
      names: string[]; // Source names that match the key
    }[];
  };
};

export const ALL_SOURCES = [
  "1dex",
  "aldrin",
  "aldrin_v2",
  "alphaq",
  "aquifer",
  "bonkswap",
  "boop.fun",
  "boop_fun",
  "byreal",
  "crema",
  "cropper",
  "defituna",
  "dexlab",
  "dynamic bonding curve",
  "dynamic_bonding_curve",
  "fluxbeam",
  "gavel",
  "goonfi",
  "goosefx gamma",
  "goosefx_gamma",
  "guacswap",
  "heaven",
  "helium network",
  "helium_network",
  "humidifi",
  "invariant",
  "lifinity",
  "lifinity_v2",
  "mercurial",
  "meteora damm",
  "meteora dlmm",
  "meteora",
  "meteora_damm_v2",
  "meteora_dlmm",
  "moonit",
  "obric",
  "obric_v2",
  "openbook",
  "openbook_v2",
  "orca",
  "orca_v1",
  "orca_v2",
  "pancakeswap",
  "penguin",
  "perena",
  "perps",
  "phoenix",
  "pump.fun amm",
  "pump.fun",
  "pump_fun",
  "pump_fun_amm",
  "raydium clmm",
  "raydium cp",
  "raydium launchlab",
  "raydium",
  "raydium_clmm",
  "raydium_cp",
  "raydium_launchlab",
  "saber (decimals)",
  "saber",
  "saber_(decimals)",
  "sanctum infinity",
  "sanctum",
  "sanctum_infinity",
  "saros",
  "solayer",
  "solfi",
  "solfi_v2",
  "stabble stable swap",
  "stabble weighted swap",
  "stabble_stable_swap",
  "stabble_weighted_swap",
  "stepn",
  "tesserav",
  "token swap",
  "token_swap",
  "virtuals",
  "whirlpool",
  "woofi",
  "zerofi",
] as const;
