// Auto-generated file. Do not edit manually.
// Generated on 2025-09-12T13:51:17.376Z
// This file contains available liquidity sources for Jupiter DEX integration

export const SOURCES = {
  strategy: "jupiter",
  sources: {
    "34268394551451": [
      { key: "Invariant", names: ["invariant"] },
      { key: "Byreal", names: ["byreal"] },
      {
        key: "Stabble Weighted Swap",
        names: ["stabble weighted swap", "stabble_weighted_swap"],
      },
      {
        key: "Saber (Decimals)",
        names: ["saber (decimals)", "saber_(decimals)"],
      },
      {
        key: "Meteora DAMM v2",
        names: ["meteora damm v2", "meteora_damm_v2", "meteora damm"],
      },
      { key: "OpenBook V2", names: ["openbook v2", "openbook_v2", "openbook"] },
      { key: "SolFi V2", names: ["solfi v2", "solfi_v2", "solfi"] },
      { key: "Guacswap", names: ["guacswap"] },
      {
        key: "Sanctum Infinity",
        names: ["sanctum infinity", "sanctum_infinity"],
      },
      { key: "DexLab", names: ["dexlab"] },
      { key: "Pump.fun", names: ["pump.fun", "pump_fun"] },
      { key: "Boop.fun", names: ["boop.fun", "boop_fun"] },
      { key: "Pump.fun Amm", names: ["pump.fun amm", "pump_fun_amm"] },
      { key: "Obric V2", names: ["obric v2", "obric_v2", "obric"] },
      { key: "Sanctum", names: ["sanctum"] },
      { key: "Penguin", names: ["penguin"] },
      { key: "Whirlpool", names: ["whirlpool"] },
      { key: "Virtuals", names: ["virtuals"] },
      { key: "Meteora DLMM", names: ["meteora dlmm", "meteora_dlmm"] },
      { key: "SolFi", names: ["solfi"] },
      { key: "Aldrin V2", names: ["aldrin v2", "aldrin_v2", "aldrin"] },
      { key: "HumidiFi", names: ["humidifi"] },
      { key: "Aldrin", names: ["aldrin"] },
      { key: "Saber", names: ["saber"] },
      { key: "Raydium CLMM", names: ["raydium clmm", "raydium_clmm"] },
      { key: "Phoenix", names: ["phoenix"] },
      { key: "Token Swap", names: ["token swap", "token_swap"] },
      { key: "Gavel", names: ["gavel"] },
      { key: "FluxBeam", names: ["fluxbeam"] },
      { key: "Bonkswap", names: ["bonkswap"] },
      { key: "Aquifer", names: ["aquifer"] },
      { key: "Orca V1", names: ["orca v1", "orca_v1", "orca"] },
      { key: "ZeroFi", names: ["zerofi"] },
      { key: "GoonFi", names: ["goonfi"] },
      { key: "Perena", names: ["perena"] },
      {
        key: "Dynamic Bonding Curve",
        names: ["dynamic bonding curve", "dynamic_bonding_curve"],
      },
      { key: "1DEX", names: ["1dex"] },
      { key: "TesseraV", names: ["tesserav"] },
      { key: "Helium Network", names: ["helium network", "helium_network"] },
      { key: "Orca V2", names: ["orca v2", "orca_v2", "orca"] },
      { key: "Mercurial", names: ["mercurial"] },
      {
        key: "Stabble Stable Swap",
        names: ["stabble stable swap", "stabble_stable_swap"],
      },
      { key: "Heaven", names: ["heaven"] },
      { key: "PancakeSwap", names: ["pancakeswap"] },
      { key: "Lifinity V2", names: ["lifinity v2", "lifinity_v2", "lifinity"] },
      { key: "Perps", names: ["perps"] },
      { key: "Cropper", names: ["cropper"] },
      { key: "StepN", names: ["stepn"] },
      { key: "Saros", names: ["saros"] },
      { key: "Crema", names: ["crema"] },
      { key: "Woofi", names: ["woofi"] },
      { key: "Meteora", names: ["meteora"] },
      { key: "Solayer", names: ["solayer"] },
      { key: "GooseFX GAMMA", names: ["goosefx gamma", "goosefx_gamma"] },
      { key: "Moonit", names: ["moonit"] },
      { key: "Raydium", names: ["raydium"] },
      { key: "Raydium CP", names: ["raydium cp", "raydium_cp"] },
      {
        key: "Raydium Launchlab",
        names: ["raydium launchlab", "raydium_launchlab"],
      },
    ],
  },
} as {
  strategy: string;
  sources: {
    [chainId: number]: {
      key: string; // Source key used by the DEX API
      names: string[]; // Source names that match the key
    }[];
  };
};

export const ALL_SOURCES = [
  "1dex",
  "aldrin v2",
  "aldrin",
  "aldrin_v2",
  "aquifer",
  "bonkswap",
  "boop.fun",
  "boop_fun",
  "byreal",
  "crema",
  "cropper",
  "dexlab",
  "dynamic bonding curve",
  "dynamic_bonding_curve",
  "fluxbeam",
  "gavel",
  "goonfi",
  "goosefx gamma",
  "goosefx_gamma",
  "guacswap",
  "heaven",
  "helium network",
  "helium_network",
  "humidifi",
  "invariant",
  "lifinity v2",
  "lifinity",
  "lifinity_v2",
  "mercurial",
  "meteora damm v2",
  "meteora damm",
  "meteora dlmm",
  "meteora",
  "meteora_damm_v2",
  "meteora_dlmm",
  "moonit",
  "obric v2",
  "obric",
  "obric_v2",
  "openbook v2",
  "openbook",
  "openbook_v2",
  "orca v1",
  "orca v2",
  "orca",
  "orca_v1",
  "orca_v2",
  "pancakeswap",
  "penguin",
  "perena",
  "perps",
  "phoenix",
  "pump.fun amm",
  "pump.fun",
  "pump_fun",
  "pump_fun_amm",
  "raydium clmm",
  "raydium cp",
  "raydium launchlab",
  "raydium",
  "raydium_clmm",
  "raydium_cp",
  "raydium_launchlab",
  "saber (decimals)",
  "saber",
  "saber_(decimals)",
  "sanctum infinity",
  "sanctum",
  "sanctum_infinity",
  "saros",
  "solayer",
  "solfi v2",
  "solfi",
  "solfi_v2",
  "stabble stable swap",
  "stabble weighted swap",
  "stabble_stable_swap",
  "stabble_weighted_swap",
  "stepn",
  "tesserav",
  "token swap",
  "token_swap",
  "virtuals",
  "whirlpool",
  "woofi",
  "zerofi",
] as const;
