name: API E2E Tests

on:
  deployment_status:

jobs:
  e2e-api-tests:
    if: |
      github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
      - name: Run API e2e tests
        run: yarn test:e2e-api
        env:
          E2E_TESTS_SWAP_API_BASE_URL: ${{ github.event.deployment_status.environment_url }}
          TEST_MODE: e2e-api
