name: API E2E Tests

on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"

jobs:
  e2e-api-tests:
    if: |
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.project.name == 'app-frontend-v3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - uses: ./.github/actions/setup
      # For now, we only need Chromium.
      - name: Run API e2e tests
        # https://synpress.io/docs/guides/ci#ci
        run: yarn test:e2e-api
        env:
          E2E_TESTS_SWAP_API_BASE_URL: ${{ github.event.client_payload.url }}
