name: API E2E Tests

on:
  deployment_status:

jobs:
  e2e-api-tests:
    if: |
      github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.environment_url, 'app-frontend-v3')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - uses: ./.github/actions/setup
      # For now, we only need Chromium.
      - name: Run API e2e tests
        # https://synpress.io/docs/guides/ci#ci
        run: yarn test:e2e-api
        env:
          E2E_TESTS_SWAP_API_BASE_URL: ${{ github.event.client_payload.url }}
